### PR TITLE
fix: support for RTL in skeleton paragraphs (fixes #1069)

### LINKED ISSUE #1069: d2l-skeletize-paragraph does not support RTL
None of the paragraph skeletons currently supports RTL.

image

### PR DESCRIPTION
**Pull request by dlockhart**
I added RTL tests for all the skeleton stuff as well, so expect a bunch of new diffs. I renamed the existing LTR visual diff files, so they should be unchanged.

### CODE REVIEW

File: components/skeleton/skeleton-mixin.js [hunk 1]
```diff
@@ -72,6 +72,12 @@ export const skeletonStyles = css`
 		content: '\\A \\A \\A \\A';
 		white-space: pre;
 	}
+	:host([skeleton][dir="rtl"]) .d2l-skeletize-paragraph-2,
+	:host([skeleton][dir="rtl"]) .d2l-skeletize-paragraph-3,
+	:host([skeleton][dir="rtl"]) .d2l-skeletize-paragraph-5 {
```
Comment (dlockhart) [inline components/skeleton/skeleton-mixin.js:77]: I ran this through a CSS autoprefixer with our current support settings and the `-webkit-*` prefix isn't needed.

File: components/skeleton/skeleton-mixin.js [hunk 2]
```diff
@@ -131,7 +138,7 @@ export const skeletonStyles = css`
 	}
 `;
 
-export const SkeletonMixin = superclass => class extends superclass {
+export const SkeletonMixin = superclass => class extends RtlMixin(superclass) {
```
Comment (dlockhart) [inline components/skeleton/skeleton-mixin.js:141]: Alright this should fix the initial issues. I was testing it in the demo container which puts `dir="rtl"` right on the element. Without the `RtlMixin`, it wasn't picking up a `dir="rtl"` on the document.

Since having someone use `SkeletonMixin` AND `RtlMixin` -- even within our own components -- is quite common, I've added the de-duper to `RtlMixin`.

**Review by dbatiste — APPROVED** [review]

File: components/skeleton/test/skeleton.visual-diff.html [hunk 3]
```diff
@@ -13,6 +13,10 @@
 			import '../demo/skeleton-test-paragraph.js';
 			import '../demo/skeleton-test-width.js';
 		</script>
+		<script>
```
Comment (dbatiste) [inline components/skeleton/test/skeleton.visual-diff.html:16]: Maybe try moving this before the imports module.

**Review by svanherk — APPROVED** [review]
Looks good to me
